replicaCount: 2

image:
  repository: "gcr.io/google-samples/hello-app"
  pullPolicy: IfNotPresent
  tag: "2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: hello-world.berber
      paths:
        - /
      backend:
        serviceName: demo-app
        servicePort: 8080
  tls: []

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 200m
     memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 2
  httpGet:
    path: /
    port: 8080

nodeSelector: {}

tolerations: []

affinity: {}
