name: Docker Image CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          cd demo-app-code/ && docker build . --tag ${{ env.IMAGE_NAME }} \
          --label "runnumber=${GITHUB_RUN_ID}"
  
    - uses: actions/checkout@v2

    - name: Log in to registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
          # Change all uppercase to lowercase
          IMAGE_ID=${{ env.REGISTRY }}/$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID
          echo $IMAGE_ID 
          docker push $IMAGE_ID
          docker images

    - name: Update Docker image Tag in Helm chart
      run: |
          # Substitue tag in helm/demo-app/values.yaml
          VERSION=v4.2.0 
          BINARY=yq_linux_amd64
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} \
          -O /usr/bin/yq && chmod +x /usr/bin/yq
          yq e -i '.image.tag = "$IMAGE_ID"' ./helm/demo-app/values.yaml