name: Docker Image CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          cd demo-app-code/ && docker build . --tag ${{ env.IMAGE_NAME }} \
          --label "runnumber=${GITHUB_RUN_ID}"
  
    - uses: actions/checkout@v2

    - name: Log in to registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
          # Change all uppercase to lowercase
          IMAGE_ID=${{ env.REGISTRY }}/$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID
          echo $IMAGE_ID 
          docker push $IMAGE_ID
          docker images

          sudo snap install yq
          yq e -i ".image.tag = \"${{ github.sha }}"\" ./helm/demo-app/values.yaml
          cat ./helm/demo-app/values.yaml

  - uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: Automated Change
    branch: feature-123
    commit_options: '--no-verify --signoff'
    file_pattern: ./helm/demo-app/values.yaml
    repository: .
    commit_user_name: My GitHub Actions Bot
    commit_user_email: my-github-actions-bot@example.org
    commit_author: Author <actions@github.com>
    tagging_message: 'v1.0.0'
    status_options: '--untracked-files=no'
    add_options: '-u'
    push_options: '--force'
    skip_dirty_check: true    
    skip_fetch: true        
    disable_globbing: true
