name: Docker Image CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          IMAGE_TAG=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$(date +%s)
          cd demo-app-code/ && docker build . --tag $IMAGE_TAG --label "runnumber=${GITHUB_RUN_ID}"
  # The "deploy" workflow
  push:
    runs-on: ubuntu-latest
    needs: [build]
    # Only run this workflow if it is master branch on push event
    if: ${{ github.ref == 'refs/heads/workflow' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2

    - name: Log in to registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_TAG
          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_TAG=$IMAGE_TAG

          # Change all uppercase to lowercase
          #IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          #echo IMAGE_ID=$IMAGE_ID
          #docker tag $IMAGE_NAME $IMAGE_ID
          #docker push $IMAGE_ID