name: Docker Image CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd demo-app-code/ && docker build . --tag demo-app:$(date +%s)
  # The "deploy" workflow
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    # Only run this workflow if it is master branch on push event
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2

    # Deploy to Docker registry
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: wilsontanwm/gosimple
        tag_with_ref: true